//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureSpec) DeepCopyInto(out *CaptureSpec) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.MaxSnapshots != nil {
		in, out := &in.MaxSnapshots, &out.MaxSnapshots
		*out = new(int32)
		**out = **in
	}
	if in.MaxDuration != nil {
		in, out := &in.MaxDuration, &out.MaxDuration
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureSpec.
func (in *CaptureSpec) DeepCopy() *CaptureSpec {
	if in == nil {
		return nil
	}
	out := new(CaptureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointRestoreOperator) DeepCopyInto(out *CheckpointRestoreOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointRestoreOperator.
func (in *CheckpointRestoreOperator) DeepCopy() *CheckpointRestoreOperator {
	if in == nil {
		return nil
	}
	out := new(CheckpointRestoreOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CheckpointRestoreOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointRestoreOperatorList) DeepCopyInto(out *CheckpointRestoreOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CheckpointRestoreOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointRestoreOperatorList.
func (in *CheckpointRestoreOperatorList) DeepCopy() *CheckpointRestoreOperatorList {
	if in == nil {
		return nil
	}
	out := new(CheckpointRestoreOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CheckpointRestoreOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointRestoreOperatorSpec) DeepCopyInto(out *CheckpointRestoreOperatorSpec) {
	*out = *in
	in.GlobalPolicies.DeepCopyInto(&out.GlobalPolicies)
	if in.ContainerPolicies != nil {
		in, out := &in.ContainerPolicies, &out.ContainerPolicies
		*out = make([]ContainerPolicySpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodPolicies != nil {
		in, out := &in.PodPolicies, &out.PodPolicies
		*out = make([]PodPolicySpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NamespacePolicies != nil {
		in, out := &in.NamespacePolicies, &out.NamespacePolicies
		*out = make([]NamespacePolicySpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointRestoreOperatorSpec.
func (in *CheckpointRestoreOperatorSpec) DeepCopy() *CheckpointRestoreOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(CheckpointRestoreOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointRestoreOperatorStatus) DeepCopyInto(out *CheckpointRestoreOperatorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointRestoreOperatorStatus.
func (in *CheckpointRestoreOperatorStatus) DeepCopy() *CheckpointRestoreOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(CheckpointRestoreOperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointSchedule) DeepCopyInto(out *CheckpointSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointSchedule.
func (in *CheckpointSchedule) DeepCopy() *CheckpointSchedule {
	if in == nil {
		return nil
	}
	out := new(CheckpointSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CheckpointSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointScheduleList) DeepCopyInto(out *CheckpointScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CheckpointSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointScheduleList.
func (in *CheckpointScheduleList) DeepCopy() *CheckpointScheduleList {
	if in == nil {
		return nil
	}
	out := new(CheckpointScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CheckpointScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointScheduleSpec) DeepCopyInto(out *CheckpointScheduleSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.ContainerNames != nil {
		in, out := &in.ContainerNames, &out.ContainerNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Triggers.DeepCopyInto(&out.Triggers)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointScheduleSpec.
func (in *CheckpointScheduleSpec) DeepCopy() *CheckpointScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(CheckpointScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckpointScheduleStatus) DeepCopyInto(out *CheckpointScheduleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastCheckpointTime != nil {
		in, out := &in.LastCheckpointTime, &out.LastCheckpointTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckpointScheduleStatus.
func (in *CheckpointScheduleStatus) DeepCopy() *CheckpointScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(CheckpointScheduleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerCheckpoint) DeepCopyInto(out *ContainerCheckpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerCheckpoint.
func (in *ContainerCheckpoint) DeepCopy() *ContainerCheckpoint {
	if in == nil {
		return nil
	}
	out := new(ContainerCheckpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerPolicySpec) DeepCopyInto(out *ContainerPolicySpec) {
	*out = *in
	if in.RetainOrphan != nil {
		in, out := &in.RetainOrphan, &out.RetainOrphan
		*out = new(bool)
		**out = **in
	}
	if in.MaxCheckpoints != nil {
		in, out := &in.MaxCheckpoints, &out.MaxCheckpoints
		*out = new(int)
		**out = **in
	}
	if in.MaxCheckpointSize != nil {
		in, out := &in.MaxCheckpointSize, &out.MaxCheckpointSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxTotalSize != nil {
		in, out := &in.MaxTotalSize, &out.MaxTotalSize
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerPolicySpec.
func (in *ContainerPolicySpec) DeepCopy() *ContainerPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ContainerPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForensicSnapshotChain) DeepCopyInto(out *ForensicSnapshotChain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForensicSnapshotChain.
func (in *ForensicSnapshotChain) DeepCopy() *ForensicSnapshotChain {
	if in == nil {
		return nil
	}
	out := new(ForensicSnapshotChain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ForensicSnapshotChain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForensicSnapshotChainList) DeepCopyInto(out *ForensicSnapshotChainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ForensicSnapshotChain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForensicSnapshotChainList.
func (in *ForensicSnapshotChainList) DeepCopy() *ForensicSnapshotChainList {
	if in == nil {
		return nil
	}
	out := new(ForensicSnapshotChainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ForensicSnapshotChainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForensicSnapshotChainSpec) DeepCopyInto(out *ForensicSnapshotChainSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.ContainerNames != nil {
		in, out := &in.ContainerNames, &out.ContainerNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Capture.DeepCopyInto(&out.Capture)
	out.Integrity = in.Integrity
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForensicSnapshotChainSpec.
func (in *ForensicSnapshotChainSpec) DeepCopy() *ForensicSnapshotChainSpec {
	if in == nil {
		return nil
	}
	out := new(ForensicSnapshotChainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForensicSnapshotChainStatus) DeepCopyInto(out *ForensicSnapshotChainStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.LastSnapshotTime != nil {
		in, out := &in.LastSnapshotTime, &out.LastSnapshotTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.SnapshotChainRecords != nil {
		in, out := &in.SnapshotChainRecords, &out.SnapshotChainRecords
		*out = make([]SnapshotChainRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForensicSnapshotChainStatus.
func (in *ForensicSnapshotChainStatus) DeepCopy() *ForensicSnapshotChainStatus {
	if in == nil {
		return nil
	}
	out := new(ForensicSnapshotChainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalPolicySpec) DeepCopyInto(out *GlobalPolicySpec) {
	*out = *in
	if in.RetainOrphan != nil {
		in, out := &in.RetainOrphan, &out.RetainOrphan
		*out = new(bool)
		**out = **in
	}
	if in.MaxCheckpointsPerNamespaces != nil {
		in, out := &in.MaxCheckpointsPerNamespaces, &out.MaxCheckpointsPerNamespaces
		*out = new(int)
		**out = **in
	}
	if in.MaxCheckpointsPerPod != nil {
		in, out := &in.MaxCheckpointsPerPod, &out.MaxCheckpointsPerPod
		*out = new(int)
		**out = **in
	}
	if in.MaxCheckpointsPerContainer != nil {
		in, out := &in.MaxCheckpointsPerContainer, &out.MaxCheckpointsPerContainer
		*out = new(int)
		**out = **in
	}
	if in.MaxCheckpointSize != nil {
		in, out := &in.MaxCheckpointSize, &out.MaxCheckpointSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxTotalSizePerNamespace != nil {
		in, out := &in.MaxTotalSizePerNamespace, &out.MaxTotalSizePerNamespace
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxTotalSizePerPod != nil {
		in, out := &in.MaxTotalSizePerPod, &out.MaxTotalSizePerPod
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxTotalSizePerContainer != nil {
		in, out := &in.MaxTotalSizePerContainer, &out.MaxTotalSizePerContainer
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalPolicySpec.
func (in *GlobalPolicySpec) DeepCopy() *GlobalPolicySpec {
	if in == nil {
		return nil
	}
	out := new(GlobalPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegritySpec) DeepCopyInto(out *IntegritySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegritySpec.
func (in *IntegritySpec) DeepCopy() *IntegritySpec {
	if in == nil {
		return nil
	}
	out := new(IntegritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacePolicySpec) DeepCopyInto(out *NamespacePolicySpec) {
	*out = *in
	if in.RetainOrphan != nil {
		in, out := &in.RetainOrphan, &out.RetainOrphan
		*out = new(bool)
		**out = **in
	}
	if in.MaxCheckpoints != nil {
		in, out := &in.MaxCheckpoints, &out.MaxCheckpoints
		*out = new(int)
		**out = **in
	}
	if in.MaxCheckpointSize != nil {
		in, out := &in.MaxCheckpointSize, &out.MaxCheckpointSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxTotalSize != nil {
		in, out := &in.MaxTotalSize, &out.MaxTotalSize
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacePolicySpec.
func (in *NamespacePolicySpec) DeepCopy() *NamespacePolicySpec {
	if in == nil {
		return nil
	}
	out := new(NamespacePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodPolicySpec) DeepCopyInto(out *PodPolicySpec) {
	*out = *in
	if in.RetainOrphan != nil {
		in, out := &in.RetainOrphan, &out.RetainOrphan
		*out = new(bool)
		**out = **in
	}
	if in.MaxCheckpoints != nil {
		in, out := &in.MaxCheckpoints, &out.MaxCheckpoints
		*out = new(int)
		**out = **in
	}
	if in.MaxCheckpointSize != nil {
		in, out := &in.MaxCheckpointSize, &out.MaxCheckpointSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxTotalSize != nil {
		in, out := &in.MaxTotalSize, &out.MaxTotalSize
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodPolicySpec.
func (in *PodPolicySpec) DeepCopy() *PodPolicySpec {
	if in == nil {
		return nil
	}
	out := new(PodPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRestore) DeepCopyInto(out *PodRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRestore.
func (in *PodRestore) DeepCopy() *PodRestore {
	if in == nil {
		return nil
	}
	out := new(PodRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRestoreList) DeepCopyInto(out *PodRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRestoreList.
func (in *PodRestoreList) DeepCopy() *PodRestoreList {
	if in == nil {
		return nil
	}
	out := new(PodRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRestoreSpec) DeepCopyInto(out *PodRestoreSpec) {
	*out = *in
	if in.Checkpoints != nil {
		in, out := &in.Checkpoints, &out.Checkpoints
		*out = make([]ContainerCheckpoint, len(*in))
		copy(*out, *in)
	}
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRestoreSpec.
func (in *PodRestoreSpec) DeepCopy() *PodRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(PodRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRestoreStatus) DeepCopyInto(out *PodRestoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRestoreStatus.
func (in *PodRestoreStatus) DeepCopy() *PodRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(PodRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcePercentThreshold) DeepCopyInto(out *ResourcePercentThreshold) {
	*out = *in
	if in.Upper != nil {
		in, out := &in.Upper, &out.Upper
		*out = new(int)
		**out = **in
	}
	if in.Lower != nil {
		in, out := &in.Lower, &out.Lower
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePercentThreshold.
func (in *ResourcePercentThreshold) DeepCopy() *ResourcePercentThreshold {
	if in == nil {
		return nil
	}
	out := new(ResourcePercentThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceThresholdSpec) DeepCopyInto(out *ResourceThresholdSpec) {
	*out = *in
	if in.CPUPercent != nil {
		in, out := &in.CPUPercent, &out.CPUPercent
		*out = new(ResourcePercentThreshold)
		(*in).DeepCopyInto(*out)
	}
	if in.MemoryPercent != nil {
		in, out := &in.MemoryPercent, &out.MemoryPercent
		*out = new(ResourcePercentThreshold)
		(*in).DeepCopyInto(*out)
	}
	if in.PollIntervalSeconds != nil {
		in, out := &in.PollIntervalSeconds, &out.PollIntervalSeconds
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceThresholdSpec.
func (in *ResourceThresholdSpec) DeepCopy() *ResourceThresholdSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceThresholdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotChainRecord) DeepCopyInto(out *SnapshotChainRecord) {
	*out = *in
	in.SnapshotTime.DeepCopyInto(&out.SnapshotTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotChainRecord.
func (in *SnapshotChainRecord) DeepCopy() *SnapshotChainRecord {
	if in == nil {
		return nil
	}
	out := new(SnapshotChainRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggersSpec) DeepCopyInto(out *TriggersSpec) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.ResourceThreshold != nil {
		in, out := &in.ResourceThreshold, &out.ResourceThreshold
		*out = new(ResourceThresholdSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OnKubernetesEvents != nil {
		in, out := &in.OnKubernetesEvents, &out.OnKubernetesEvents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggersSpec.
func (in *TriggersSpec) DeepCopy() *TriggersSpec {
	if in == nil {
		return nil
	}
	out := new(TriggersSpec)
	in.DeepCopyInto(out)
	return out
}
