{{- if .Values.checkpointSyncer.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "checkpoint-restore-operator.checkpointSyncer.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "checkpoint-restore-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: checkpoint-syncer
{{- end }}
