---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - criu.org
  resources:
  - checkpointrestoreoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - criu.org
  resources:
  - checkpointrestoreoperators/finalizers
  verbs:
  - update
- apiGroups:
  - criu.org
  resources:
  - checkpointrestoreoperators/status
  verbs:
  - get
  - patch
  - update
