apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: forensic-signing-secret-reader
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: checkpoint-restore-operator
    app.kubernetes.io/part-of: checkpoint-restore-operator
    app.kubernetes.io/managed-by: kustomize
  name: forensic-signing-secret-reader
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - forensic-signing-key
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: forensic-signing-secret-reader
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: checkpoint-restore-operator
    app.kubernetes.io/part-of: checkpoint-restore-operator
    app.kubernetes.io/managed-by: kustomize
  name: forensic-signing-secret-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: forensic-signing-secret-reader
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: system