apiVersion: criu.org/v1
kind: CheckpointRestoreOperator
metadata:
  labels:
    app.kubernetes.io/name: checkpointrestoreoperator
    app.kubernetes.io/instance: checkpointrestoreoperator-sample
    app.kubernetes.io/part-of: checkpoint-restore-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: checkpoint-restore-operator
  name: checkpointrestoreoperator-sample
spec:
  checkpointDirectory: /var/lib/kubelet/checkpoints
  applyPoliciesImmediately: true
  globalPolicy:
    maxCheckpointsPerNamespace: 50
    maxCheckpointsPerPod: 30
    maxCheckpointsPerContainer: 10
    maxCheckpointSize: 500
    maxTotalSizePerNamespace: 500
    maxTotalSizePerPod: 500
    maxTotalSizePerContainer: 500
  containerPolicies:
    - namespace: default
      pod: nginx-deployment-85bfd45d84-hq752
      container: nginx
      maxCheckpoints: 13
      maxCheckpointSize: 500
      maxTotalSize: 500
  podPolicies:
    - namespace: default
      pod: nginx-deployment-85bfd45d84-hq752
      maxCheckpoints: 10
      maxCheckpointSize: 500
      maxTotalSize: 500
  namespacePolicies:
    - namespace: default
      maxCheckpoints: 5
      maxCheckpointSize: 500
      maxTotalSize: 500