## Append samples of your project ##
resources:
- _v1_checkpointrestoreoperator.yaml
- criu_v1_checkpointschedule.yaml
- v1_forensicsnapshotchain.yaml
- criu_v1_podrestore.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
