apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cro.fullname" . }}-leader-election-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cro.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cro.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "cro.saName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cro.fullname" . }}-manager-role
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
- apiGroups: ["criu.org"]
  resources: ["checkpointrestoreoperators"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: ["criu.org"]
  resources: ["checkpointrestoreoperators/finalizers"]
  verbs: ["update"]
- apiGroups: ["criu.org"]
  resources: ["checkpointrestoreoperators/status"]
  verbs: ["get","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cro.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cro.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "cro.saName" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.metrics.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cro.fullname" . }}-metrics-reader
rules:
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cro.fullname" . }}-proxy-role
rules:
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cro.fullname" . }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cro.fullname" . }}-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "cro.saName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

