{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cro.fullname" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: checkpoint-restore-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
{{- end }}

