{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cro.saName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: checkpoint-restore-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
