name: verify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Install ShellCheck and shfmt
        run: |
          sudo apt update
          sudo apt install -y shellcheck shfmt

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          only-new-issues: true
          args: --timeout=5m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: codespell
        uses: codespell-project/actions-codespell@v2
        with:
          skip: vendor,*.svg

      - name: ShellCheck and shfmt
        run: |
          shellcheck ./test/*.sh
          shfmt -d ./test/*.sh

  gomod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: verify go.mod/go.sum
        run: |
          make vendor
          git diff --exit-code

  lint_markdown:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: "main"
          filters: |
            md:
              - 'README.md'
              - '.github/workflows/verify.yml'

      - name: Lint markdown
        if: steps.changes.outputs.md == 'true'
        uses: DavidAnson/markdownlint-cli2-action@v10
        with:
          globs: |
            README.md
